version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    target-branch: main

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: monthly
    target-branch: main

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    target-branch: main
