import { svelte } from '@sveltejs/vite-plugin-svelte';
import { defineConfig } from 'vite';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = fileURLToPath(new URL('.', import.meta.url));
const staticOutput = resolve(projectRoot, '../internal/httpapi/static');

export default defineConfig({
  root: projectRoot,
  plugins: [
    svelte(),
    {
      name: 'preserve-go-embed-placeholder',
      closeBundle() {
        writeFileSync(
          resolve(staticOutput, 'placeholder.txt'),
          'Frontend assets are generated by npm --prefix web run build.\n'
        );
      }
    }
  ],
  build: {
    outDir: staticOutput,
    emptyOutDir: true,
    sourcemap: false,
    target: 'es2022'
  },
  server: {
    proxy: {
      '/api': 'http://127.0.0.1:8080',
      '/healthz': 'http://127.0.0.1:8080'
    }
  }
});
